version: '3.8'
services:
  web:
    build: ./
    restart: always
    volumes:
      - "/var/log/deviotmon:/app/logs"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine

    # запросы с внешнего порта 80 перенаправляем на внутренний порт 80
    ports:
      - "3000:5000"

    volumes:
      # При сборке скопировать созданный конфиг nginx из исходной директории 
      # в контейнер и сохранить его в директорию /etc/nginx/conf.d/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - web